config/routes.rb
Rails.application.routes.draw do
  resources :quizzes
  resources :questions
  resources :subgenres
  resources :genres
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'home#index'
  post '/quizzes/:id', to: 'quizzes#submit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subgenre
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
    @questions.sort! {|a,b| a.text <=> b.text}

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json  { render :json => @question }
      end
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:subgenre_id, :description, :choice1, :choice2, :choice3, :choice4, :correct1, :correct2, :correct3, :correct4)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subgenre_id %>
    <%= form.text_field :subgenre_id, id: :question_subgenre_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :question_description %>
  </div>

  <div class="field">
    <%= form.label :choice1 %>
    <%= form.text_field :choice1, id: :question_choice1 %>
  </div>

  <div class="field">
    <%= form.label :choice2 %>
    <%= form.text_field :choice2, id: :question_choice2 %>
  </div>

  <div class="field">
    <%= form.label :choice3 %>
    <%= form.text_field :choice3, id: :question_choice3 %>
  </div>

  <div class="field">
    <%= form.label :choice4 %>
    <%= form.text_field :choice4, id: :question_choice4 %>
  </div>

  <div class="field">
    <%= form.label :correct1 %>
    <%= form.check_box :correct1, id: :question_correct1 %>
  </div>

  <div class="field">
    <%= form.label :correct2 %>
    <%= form.check_box :correct2, id: :question_correct2 %>
  </div>

  <div class="field">
    <%= form.label :correct3 %>
    <%= form.check_box :correct3, id: :question_correct3 %>
  </div>

  <div class="field">
    <%= form.label :correct4 %>
    <%= form.check_box :correct4, id: :question_correct4 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Subgenre</th>
      <th>Description</th>
      <th>Choice1</th>
      <th>Choice2</th>
      <th>Choice3</th>
      <th>Choice4</th>
      <th>Correct1</th>
      <th>Correct2</th>
      <th>Correct3</th>
      <th>Correct4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.subgenre %></td>
        <td><%= question.description %></td>
        <td><%= question.choice1 %></td>
        <td><%= question.choice2 %></td>
        <td><%= question.choice3 %></td>
        <td><%= question.choice4 %></td>
        <td><%= question.correct1 %></td>
        <td><%= question.correct2 %></td>
        <td><%= question.correct3 %></td>
        <td><%= question.correct4 %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subgenre:</strong>
  <%= @question.subgenre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
</p>

<p>
  <strong>Choice1:</strong>
  <%= @question.choice1 %>
</p>

<p>
  <strong>Choice2:</strong>
  <%= @question.choice2 %>
</p>

<p>
  <strong>Choice3:</strong>
  <%= @question.choice3 %>
</p>

<p>
  <strong>Choice4:</strong>
  <%= @question.choice4 %>
</p>

<p>
  <strong>Correct1:</strong>
  <%= @question.correct1 %>
</p>

<p>
  <strong>Correct2:</strong>
  <%= @question.correct2 %>
</p>

<p>
  <strong>Correct3:</strong>
  <%= @question.correct3 %>
</p>

<p>
  <strong>Correct4:</strong>
  <%= @question.correct4 %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>