config/routes.rb
Rails.application.routes.draw do
  resources :quizzes
  resources :questions
  resources :subgenres
  resources :genres
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'home#index'
  post '/quizzes/:id', to: 'quizzes#submit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
    #@questions = Question.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  def show
  end

  # GET /quizzes/1/edit
  def edit
  end
  def submit
        @score = 0
        @quiz= Quiz.find(params[:id])
        puts (allquestions @quiz.subgenre_id).length
        for i in 0..(allquestions @quiz.subgenre_id).length-1
            @correct= true
            if allquestions(@quiz.subgenre_id)[i].correct1
                if params[:arr][allquestions(@quiz.subgenre_id)[i].id.to_s]['1'].to_i == 0
                    @correct= false
                end
            end
            unless allquestions(@quiz.subgenre_id)[i].correct1
                if params[:arr][allquestions(@quiz.subgenre_id)[i].id.to_s]['1'].to_i == 1
                    @correct= false
                end
            end
            if allquestions(@quiz.subgenre_id)[i].correct2
                if params[:arr][allquestions(@quiz.subgenre_id)[i].id.to_s]['2'].to_i == 0
                    @correct= false
                end
            end
            unless allquestions(@quiz.subgenre_id)[i].correct2
                if params[:arr][allquestions(@quiz.subgenre_id)[i].id.to_s]['2'].to_i == 1
                    @correct= false
                end
            end
            if allquestions(@quiz.subgenre_id)[i].correct3
                if params[:arr][allquestions(@quiz.subgenre_id)[i].id.to_s]['3'].to_i == 0
                    @correct= false
                end
            end
            unless allquestions(@quiz.subgenre_id)[i].correct3
                if params[:arr][allquestions(@quiz.subgenre_id)[i].id.to_s]['3'].to_i == 1
                    @correct= false
                end
            end
            if allquestions(@quiz.subgenre_id)[i].correct4
                if params[:arr][allquestions(@quiz.subgenre_id)[i].id.to_s]['4'].to_i == 0
                    @correct= false
                end
            end
            unless allquestions(@quiz.subgenre_id)[i].correct4
                if params[:arr][allquestions(@quiz.subgenre_id)[i].id.to_s]['4'].to_i == 1
                    @correct= false
                end
            end
            if @correct
                @score = @score + 10
                puts "Hello"
            end


    end
end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:name, :subgenre_id)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper

end

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true) do |form| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :quiz_name %>
  </div>

  <div class="field">
    <%= form.label :subgenre_id %>
    <%= form.text_field :subgenre_id, id: :quiz_subgenre_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1 id="h1" style="color:gold">Editing Quiz</h1>
<br/><br/><br/><br/><br/>
<%= render 'form', quiz: @quiz %>
<br/><br/><br/>
<%= link_to 'Show', @quiz ,class:"btn btn-lg btn-success"%> |
<%= link_to 'Back', quizzes_path ,class:"btn btn-lg btn-danger"%>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>
<br/><br/><br/><br/>
<h1 id="h1">Quizzes</h1>
<br/><br/><br/>

<table>
  <thead>
    <tr>
      <th><p id="h2">Name</p></th>
      <th colspan="6"></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <br><br><br>
    <% @quizzes.each do |quiz| %>
      <tr></tr>
      <tr>
        <td colspan="2"><p id="h2"><%= quiz.name %></p></td>
        <td colspan="2"><%= link_to 'Shall We Play', quiz,class: "btn btn-lg btn-primary" %>
        <td colspan="2"><%= link_to 'Edit', edit_quiz_path(quiz),class: "btn btn-lg btn-success" %></td>
        <td colspan="2">
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br><br><br><br>
<%= link_to 'Go back to User Path', root_path,class: "btn btn-lg btn-success" %>
<%= link_to 'New Quiz', new_quiz_path,class: "btn btn-lg btn-success" %>

app/views/quizzes/new.html.erb
<h1 id="h1">New Quiz</h1>
<br/><br/><br/><br/>
<%= render 'form', quiz: @quiz %>
<br/><br/><br/><br/>
<%= link_to 'Back', quizzes_path ,class: "btn btn-lg btn-primary"%>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid bg-info">
    <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
          <p id = "h2">
            <strong>Quiz Name(Subgenre):</strong>
            <%= @quiz.name %>
          </p><br/><br/><br/><br/>


          <p>


            <%= form_for :arr, controller: "quizzes", action: "submit", method: "post", class: "form-horizontal" do |form|%>
            <% for i in 0..allquestions(@quiz.subgenre_id).length-1 %>
            <h3><span class="label label-warning" id="qid"><%= i+1 %></span><%= allquestions(@quiz.subgenre_id)[i].description.html_safe %></h3>

            <br>
            <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-primary">
              <%= form.check_box(allquestions(@quiz.subgenre_id)[i].id.to_s + '[1]') %> <%= allquestions(@quiz.subgenre_id)[i].choice1.html_safe%>
            </label>
            </br>
            </br>
            </br>
            </br>


            <label class="btn btn-primary">
              <%= form.check_box(allquestions(@quiz.subgenre_id)[i].id.to_s + '[2]') %> <%= allquestions(@quiz.subgenre_id)[i].choice2.html_safe%>
            </label>
            </br>
            </br>
            </br>
            </br>

            <label class="btn btn-primary">
              <%= form.check_box(allquestions(@quiz.subgenre_id)[i].id.to_s + '[3]') %> <%= allquestions(@quiz.subgenre_id)[i].choice3.html_safe%>
            </label>
            </br>
            </br>
            </br>
            </br>

            <label class="btn btn-primary">
              <%= form.check_box(allquestions(@quiz.subgenre_id)[i].id.to_s + '[4]') %> <%= allquestions(@quiz.subgenre_id)[i].choice4.html_safe%>
            </label>
            </br>
            </br>
            </br>
            </br>


            <% end %>
            </br>
            </br>
            </br>


            <div class="btn-group" data-toggle="buttons">
            <input type="text" class="hidden" name="id" value="<%= @quiz.id %>">
            <pre>                             <%= form.submit "Submit", :name => nil, type: "submit", class: "btn btn-lg btn-primary"%>                           </pre>
            <% end %>
          <br/>
          <br/>
          <br/>
          <pre>               <%= link_to 'Edit', edit_quiz_path(@quiz),class: "btn btn-lg btn-primary" %>                <%= link_to 'Back', quizzes_path,class: "btn btn-lg btn-success" %>              </pre>
          <!-- <%= link_to 'Back', quizzes_path,class: "btn btn-lg btn-success" %></pre> -->
<!-- <script>
  var score = 0;
  var form = document.getElementById('name-form');
  form.onsubmit = function(e){
    e.preventDefault();
    if(document.getElementsByName('value1').checked){
      if(document.getElementsByName('value1').value == true){
        score=score+10;
        var result = document.getElementById('score');
        result.innerHTML = score;
      }
    }
    else if (document.getElementsByName('value2').checked) {
      if(document.getElementsByName('value2').value == true){
        score=score+10;
        alert('heello');
        var result = document.getElementById('score');
        result.innerHTML = score;
      }
    }
    else if (document.getElementsByName('value3').checked) {
      if(document.getElementsByName('value3').value == true){
        score=score+10;
        var result = document.getElementById('score');
        result.innerHTML = score;
      }
    }
    else if (document.getElementsByName('value4').checked) {
      if(document.getElementsByName('value4').value == true){
        score=score+10;
        var result = document.getElementById('score');
        result.innerHTML = score;
      }
    }
    var result = document.getElementById('score');
    result.innerHTML = score;
}
</script> -->

app/views/quizzes/submit.html.erb
<br/>
<br/>
<br/>
<br/>
<p class="score"> The score is </p>
<br/>
<br/>
<br/>
<br/>
<p class="score"><%= @score %></p>
<br/>
<br/>
<br/>
<br/>
<%= link_to 'Quiz ended. Click to go back to Quiz index menu', quizzes_path, class: "btn btn-lg btn-primary" %>